# Generated by Django 6.0.5 on 2026-06-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=5)),
                ('bpm', models.IntegerField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('lyrics', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
