# Generated by Django 6.0.5 on 2026-06-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='youtube_link',
            new_name='youtube_url',
        ),
        migrations.AddField(
            model_name='song',
            name='chords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='bpm',
            field=models.IntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='song',
            name='key',
            field=models.CharField(default='C', max_length=10),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
