# Generated by Django 6.0.5 on 2026-06-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_rename_youtube_link_song_youtube_url_song_chords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='bpm',
        ),
        migrations.RemoveField(
            model_name='song',
            name='key',
        ),
        migrations.RemoveField(
            model_name='song',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='song',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='chords',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
